services:
  - type: web
    name: assembly-factory
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: free
    healthCheckPath: /api/design
    envVars:
      - key: PORT
        value: 80
